name: CodeSonar
on:
  push:                  # Only run onces the Pull request is created
    branches:
      - 'release/**'               # Feature Branches
  pull_request:
    branches:
      - 'release/**'       
  
jobs:
  CodeSonar_Analyze:
    permissions: write-all
    runs-on: curl-runner-set
    container:
      image: ghcr.io/codesecure-se/curl-cso-builder:8.1p0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    env:
      CAFILE: ".github/github.cert.pem" 
      TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      API_URL: https://api.github.com
      REQUEST_NUMBER: ${{ github.event.pull_request.number }}
      ROOT_TREE: "Curl-Projects" 
      PROJECT_NAME: "curl"
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
      CSONAR_HUB_URL: "http://codesonar.lan:7340" 
      CSONAR_HUB_USER: "${{ secrets.CSONAR_HUB_USER }}"
      CSONAR_HUB_PASSWORD: "${{ secrets.CSONAR_HUB_PASSWORD }}"
      CSONAR_CSHOME: /opt/codesonar
      CS_USER_HOME: /__w/curl/curl
      COMMIT_HASH: ${{ github.sha }}
      REPO_URL: "https://github.com/CodeSecure-SE/curl"    # the github.repositoryUrl is not an http-link.
      TARGET: ${{ github.base_ref }}
      IS_PR: ${{ github.event_name }}
    steps:
      - name: Set parallelism
        run:  echo "PARALLEL=`nproc`" >> $GITHUB_ENV
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Safe directory
        run: git config --global --add safe.directory `pwd`
      - name : configure
        run: autoreconf -fi; ./configure --with-openssl
      - name: Checkout CodeSonar CI-Script
        uses: actions/checkout@v4
        with:
          repository: CodeSecure-SE/codesonar_ci
          path: codesonar-scripts
      - name: Build and Analyze
        run: python3 codesonar-scripts/build_and_analyze.py codesonar.conf make -j $PARALLEL
      - name: Download results
        run: |
          echo $CSONAR_HUB_PASSWORD > hubpwfile
          $CSONAR_CSHOME/codesonar/bin/codesonar dump_warnings.py --project-file $PROJECT_NAME.prj \
          -auth password -hubuser $CSONAR_HUB_USER -hubpwfile hubpwfile  --hub $CSONAR_HUB_URL --gained-since-previous-analysis --visible-warnings "active" --sarif --sarif-detail brief -o diff.sarif
          $CSONAR_CSHOME/codesonar/bin/codesonar dump_warnings.py --project-file $PROJECT_NAME.prj  \
          -auth password -hubuser $CSONAR_HUB_USER -hubpwfile hubpwfile  --hub $CSONAR_HUB_URL \
          --sort "ascending:priority" --sort "descending:score" --visible-warnings "active" --gained-since-previous-analysis --csv -o diff.csv

          sed -i 's#/warninginstance#https://partnerdemo.codesonar.com/warninginstance#' diff.csv
          sed -i 's#.txt$#.html#' diff.csv
          cut -d, -f1,2,3,4,5,6,7,8,9,15 diff.csv > diff2.csv
          csv2md diff2.csv > diff.md
      - name: Create tgz copy of SARIF results
        run: tar czf diff.sarif.tgz diff.sarif
      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: SARIF results summary
          path: |
            diff.sarif
            diff.md
      - name: Check if diff.md has more than 2 lines
        id: check_diff
        run: |
          if [ $(wc -l < diff.md) -gt 2 ]; then
            echo "send_mail=true" >> $GITHUB_OUTPUT
          else
            echo "send_mail=false" >> $GITHUB_OUTPUT
          fi
      - name: Email results
        if: steps.check_diff.outputs.send_mail == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          subject: CodeSonar results for ${{ github.repository }}
          body: file://diff.md
          convert_markdown: true
          from: "CodeSonar Analyzer"
          to: "mark@hermeling.org"
          reply_to: "mark@hermeling.org"
          attachments: diff.sarif.tgz
      - name: cleanup
        run: rm hubpwfile
